version: '3.8'

services:
  fatwa-search-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fatwa-search-api
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY:-change-me-in-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COLLECTION_NAME=${COLLECTION_NAME:-mufti_fatwas}
      - RATE_LIMIT=${RATE_LIMIT:-20/minute}
    volumes:
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped
    networks:
      - fatwa-net

networks:
  fatwa-net:
    driver: bridge 